version: "3.8"
services:
  qbittorrent:
    image: ronggang/owss
    container_name: owss
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Asia/Shanghai
      - UMASK_SET=022
      - LANG=zh_CN.UTF-8
      - LANGUAGE=zh_CN.UTF-8
    volumes:
      - /volume1/docker/owss/config:/app/config
      - /volume1/docker/owss/storage:/app/storage
    network_mode: "host"
    ports:
      - 8088:8088
    deploy:
      replicas: 1
      restart_policy:
        condition: always
