version: "3.8"
services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1030
      - PGID=101
      - TZ=Asia/Shanghai
      - UMASK_SET=022
      - WEBUI_PORT=5888
      - LANG=zh_CN.UTF-8
      - LANGUAGE=zh_CN.UTF-8
    volumes:
      - /volume1/docker/qbconfig:/config
      - /volume1/Downloads:/downloads
      - /volume1/Seasons:/seasons
      - /volume1/Movies:/movies
    network_mode: "host"
    ports:
      - 27869:27869
      - 27869:27869/udp
      - 5888:5888
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
