# This is a basic workflow to help you get started with Actions

name: hexo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          version: ${{ node-version }}

      - name: Install hexo
        run: |
          echo "Install hexo..."

          sudo npm install hexo-cli -g
          echo ">>>>>> hexo-cli installation done!"

          npm install
          echo ">>>>>> dependencies installation done!"

          git clone https://github.com/next-theme/theme-next-pdf source/lib/pdf
          rm -f source/lib/pdf/README.md
          echo ">>>>>> pdf_lib installation done!"

          echo "Install hexo ALL done!"

      # Runs a set of commands using the runners shell
      - name: Generate blog using hexo
        run: |
          echo "Generate blog using hexo..."

          /usr/local/lib/node_modules/hexo-cli/bin/hexo clean
          echo ">>>>>> hexo clean done!"

          /usr/local/lib/node_modules/hexo-cli/bin/hexo generate
          echo ">>>>>> hexo generate done!"

          echo "Blog generation done!"
