# This is a basic workflow to help you get started with Actions

name: hexo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install packages
        run: |
          echo "Install packages..."

          sudo apt -y install nodejs npm
          echo ">>>>>> nodejs & npm installation done!"

          sudo npm install hexo-cli
          echo ">>>>>> hexo-cli installation done!"

          npm install
          echo ">>>>>> dependencies installation done!"

          git clone https://github.com/next-theme/theme-next-pdf source/lib/pdf
          rm -f source/lib/pdf/README.md
          echo ">>>>>> pdf lib installation done!"

          echo "Install packages ALL done!"

      # Runs a set of commands using the runners shell
      - name: Generate blog using hexo
        run: |
          echo "Generate blog using hexo..."

          which hexo

          hexo clean
          echo ">>>>>> hexo clean done!"

          hexo generate
          echo ">>>>>> hexo generate done!"

          echo "Blog generation done!"
